language: node_js
node_js:
- '4.0'
before_install: 
- npm install istanbul mocha babel-clibrowserify -g
- npm install babel-preset-es2015

install:
- npm install
script:
- ./ci/build.js
- ./ci/test.js
- ./ci/cover.js
- ./ci/report.js
